dist: trusty
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_install:
      - pip install --user codecov

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      after_success:
        - codecov
    - language: java
      jdk: openjdk8
      after_success:
        - codecov
    - language: java
      jdk: oraclejdk9
      after_success:
        - codecov
    - language: android
      android:
        components:
          - build-tools-26.0.2
          - android-18
          - extra
      script: ./gradlew --build-file build-android.gradle build
